### ISSUE TITLE
No files to analyze

### ISSUE THREAD

**Issue by pekonchan** [adam-moss/sonarlint#2]
![image](https://user-images.githubusercontent.com/38689834/110412160-b09ea900-80c6-11eb-9be6-90846726c828.png)

I have set the param `src` , but it show the result no files to analyze

**Comment by adam-moss** [comment]
No files to analyze normally indicates that either the src path isn't returning anything (you perhaps need `src/**/*`) or that the file types are recognised for scanning.

That being said SonarLint for CommandLine was discontinued a long time ago, so you're probably better off using one of the IDE integrations that are now available.
